### ISSUE TITLE
Hail Initialization Fails Due to Incorrect Java Version (Found Java 17 Instead of Java 8/11)

### ISSUE THREAD

**Issue by enriquea** [MedGenOL/pygskit#2]
Error:

`HailException: Hail requires Java 8 or 11, found 17.0.14`

Root Cause:

The environment (or the GitHub runner) was using the system default Java (Java 17), which is incompatible with Hail. Although the environment.yml included openjdk=11, the system-wide Java installation was taking precedence.

Solution:

Set up the correct Java version in the GitHub workflow (https://github.com/MedGenOL/pygskit/blob/main/.github/workflows/python-package-conda.yml) :

```
- name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
```
